# Generated by Django 4.2.11 on 2024-04-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instasecond', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
