# Generated by Django 4.2.11 on 2024-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instasecond', '0003_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='IvanIvanov@mail.ru', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Ivan Ivanov', max_length=50),
        ),
    ]
