# Generated by Django 4.2.11 on 2024-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instasecond', '0004_user_email_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='IvanIvanov@mail.ru', max_length=40),
        ),
    ]
