# Generated by Django 4.2.11 on 2024-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instasecond', '0006_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='IvanIvanov@mail.ru', max_length=40),
        ),
    ]
