# Generated by Django 4.2.11 on 2024-05-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instasecond', '0010_fill_tabels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='posts',
            name='header',
            field=models.CharField(max_length=50),
        ),
    ]
