# Generated by Django 4.2.11 on 2024-05-24 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instasecond', '0011_alter_posts_content_alter_posts_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='IvanIvanov@mail.ru', max_length=40)),
                ('name', models.CharField(default='Ivan Ivanov', max_length=50)),
                ('nikname', models.CharField(max_length=50, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('rate', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instasecond.profile'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instasecond.profile'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instasecond.profile'),
        ),
        migrations.AlterField(
            model_name='subs',
            name='to_whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_whom', to='instasecond.profile'),
        ),
        migrations.AlterField(
            model_name='subs',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='instasecond.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
