# Generated by Django 4.2.11 on 2024-05-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instasecond', '0012_profile_alter_comments_author_alter_likes_who_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
    ]
